version: 2
jobs:
 build:
   machine: true
   environment:
     IMAGE_NAME: "dasale/goof"
     SCAN_IMAGE_NAME: "snyklabs/goof"

   steps:
     # checkout the source code
     - checkout

     # login
     - run: |
         docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"
     # build the application image
     - run: docker build -t "$IMAGE_NAME" .

     # scan the image
     - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock $SCAN_IMAGE_NAME /bin/inline_scan analyze -s hhttps://us2.app.sysdig.com -k "$SYSDIG_SECURE_TOKEN" "$IMAGE_NAME"

     # deploy the image
     - run: docker push "$IMAGE_NAME"