version: 2
jobs:
 build:
   machine: true
   environment:
     IMAGE_NAME: "dasalebr/goof"
     SCAN_IMAGE_NAME: "sysdig/secure-inline-scan:2"

   steps:
     # checkout the source code
     - checkout

     # login
     - run: |
         docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"
     # build the application image
     - run: docker build -t "$IMAGE_NAME" .

     # scan the image
     - run: docker run --rm  quay.io/sysdig/secure-inline-scan:2 $SCAN_IMAGE_NAME  -s https://eu1.app.sysdig.com -k "$SYSDIG_SECURE_TOKEN" "$IMAGE_NAME"

     # deploy the image
     - run: docker push "$IMAGE_NAME"